export const init = () => {};
export const captureException = () => {};
export const captureMessage = () => {};
export const setUser = () => {};
export const setContext = () => {};
export const addBreadcrumb = () => {};
export const configureScope = () => {};
export const showReportDialog = () => {};
export const flush = () => Promise.resolve();
export const lastEventId = null;
export const getCurrentHub = () => ({ getClient: () => null, getScope: () => ({}) });
